---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: vault-self-signed-ca-issuer
  namespace: vault
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: vault-ca
  namespace: vault
spec:
  secretName: vault-ca-key-pair
  duration: 87600h
  renewBefore: 360h
  organization:
  - Project vault
  commonName: vault CA
  isCA: true
  keySize: 2048
  keyAlgorithm: rsa
  keyEncoding: pkcs1
  usages:
  - server auth
  - client auth
  dnsNames:
  - vaultca
  ipAddresses: []
  issuerRef:
    name: vault-self-signed-ca-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: vault-ca-issuer
  namespace: vault
spec:
  ca:
    secretName: vault-ca-key-pair