kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: cert-manager
  namespace: fleet-default
spec:
  repo: https://github.com/bcdurden/fleet-demo.git
  branch: main

  # To target specific clusters, uncomment this block
  # targets:
  # - name: example
  #   clusterSelector:
  #     matchLabels:
  #       cluster: example  
  targets:
  - clusterSelector:
      matchExpressions:
      - key: provider.cattle.io
        operator: NotIn
        values:
        - harvester

  paths:
  - "./gitops/cert-manager/crds"
  - "./gitops/cert-manager/cert-manager"