kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: longhorn
  namespace: fleet-default
spec:
  repo: ssh://git@github.com:bcdurden/fleet-demo.git

  # To target specific clusters, uncomment this block
  # targets:
  # - name: example
  #   clusterSelector:
  #     matchLabels:
  #       cluster: example

  paths:
  - "./gitops/storage/longhorn/helm"