kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: dev-cluster-templates
  namespace: fleet-local
spec:
  repo: https://github.com/bcdurden/fleet-demo.git
  branch: main  
  targets:
  - clusterName: local
  #! patch command: kubectl patch ClusterGroup -n fleet-local default --type=json -p='[{"op": "remove", "path": "/spec/selector/matchLabels/name"}]'

  paths:
  - "./gitops/clusters/dev"