externalURL: https://harbor.homelab.platformfeverdream.io

harborAdminPassword: "example-password"

updateStrategy:
  type: Recreate

ingress:
  core:
    hostname: harbor.homelab.platformfeverdream.io
  notary:
    hostname: notary.harbor.homelab.platformfeverdream.io

persistence:
  persistentVolumeClaim:
    registry:
      size: 75Gi
      storageClass: "longhorn"
    chartmuseum:
      storageClass: "longhorn"
    jobservice:
      storageClass: "longhorn"
    database:
      storageClass: "longhorn"
    redis:
      storageClass: "longhorn"
    trivy:
      storageClass: "longhorn"

# If using an external Postgres DB
# database:
#   type: external

#   external:
#     host: "postgres.example.com"
#     port: "5432"
#     username: "example-user"
#     password: "example-password"
#     coreDatabase: "registry"
#     notaryServerDatabase: "notary_server"
#     notarySignerDatabase: "notary_signer"
